config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :users
  resources :posts do 
  	resources :comments
  end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
	validates_uniqueness_of :username
	validates :fname, presence: true, length: {minimum: 3, maximum: 20}
	validates :lname, presence: true, length: {minimum: 3, maximum: 20}
	validates :dob, presence: true
	validates :username, presence: true, length: {minimum: 3, maximum: 20}
	validates :password, presence: true, length: {minimum: 3, maximum: 10}
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	def current_user
		if session[:user_id]
			@current_user = User.find(session[:user_id])
		end
	end
	def post
		@post = Post.find(params[:id])	
	end
	helper_method :current_user
	helper_method :post  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		Comment.create(
			text: params[:text],
			user_id: current_user.id,
			post_id: params[:post_id]
			)
		redirect_to '/posts'	
	end
	def show
		@comment = Comment.find(params[:id])
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if session[:user_id]
		current_user
		end
		# @current_user = session[:user_id] && User.find(session[:user_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :post, only: [:show, :destroy, :edit, :update]
	# def show
	# end   
	def index
		@posts = Post.all 
	end
	def create
		Post.create(post_params)
		redirect_to '/posts'	
	end
	def destroy
		begin
		rescue
		end
		if @post && @post.destroy
			flash[:notice] = "Your post has been deleted!"
		else
			flash[:notice] = "Sorry, we could not delete your post"
		end
		redirect_to posts_path
	end
	# def edit
	# end
	def update
		@post.update(post_params
			)
		flash[:notice] = "Post Updated Congrats"
		redirect_to '/posts'
	end
	private
	def post_params
		params.require(:post).permit(:text,:title,:image).merge(user_id: current_user.id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# Create session 
	def create
		@user = User.where("username = '#{params[:username]}'").first

		if @user && @user.password == params[:password]
   # "WELCOME #{@user.fname}!"
   session[:user_id] = @user.id
   redirect_to '/posts/new'
		else
			flash[:notice] = "Invalid username or password"
			redirect_to '/'
		end
	end
	def destroy
		session.destroy
		flash[:notice] = "You are now logged out"
		redirect_to '/'	
	end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :is_admin, only: [:index]
	def show
		@user = User.find(params[:id])   
	end   
	def index
		@users = User.all   
	end
	def create
		@user = User.new(user_params)
		if @user.save
		flash[:notice] = "Congrats on your new account"
		redirect_to '/'
		else
		render :new
		end	
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if(@user.password == params[:user][:password] && params[:user][:new_password].length > 0)
			@user.update(fname: params[:user][:fname],
				lname: params[:user][:lname],
				dob: params[:user][:dob],
				username: params[:user][:username],
				password: params[:user][:new_password]
				)
		end
		flash[:notice] = "Profile Updated Congrats"
		redirect_to '/'
	end
	def destroy
		begin
			@user = User.find(params[:id])
		rescue
		end
		if @user.id == session[:user_id]
			session.destroy
		end
		if @user && @user.destroy
			flash[:notice] = "Your account has been deleted!"
		else
			flash[:notice] = "Sorry, we could not delete you"
		end
		redirect_to users_path
	end
	private
	def user_params
		params.require(:user).permit(:fname,:lname,:dob,:username,:password)
	end
	def is_admin
		redirect_to '/' unless current_user && current_user.admin
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h4>SPEAK UP MY DEAR!</h4>
<h4>SHE WANTS TO HEAR FROM YOU</h4>
<div class = "col-md-offset-4 col-md-4">
	<%= form_tag post_comments_path(params[:post_id]) do %> 
	<div class="form-login">
		<h4>NEW COMMENT</h4>
		<%= label_tag :text, "Comment" %> 
		<%= text_field_tag :text, nil, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="wrapper">
		<%= submit_tag "", class: "btn btn-primary btn-md", value: "POST COMMENT"%>
	</div>
	<% end %>
</div>	

app/views/home/index.erb
<h4>HAVE YOUR EVER LOST YOUR MARBLES ?</h4>
<h4>JOIN OUR BLOG !!!</h4>
</br>
</br>
</br>
<% unless current_user %>
    <div class="col-md-offset-4 col-md-4">
      <div class="form-login">
        <%= form_tag login_path do %>  
        <%= label_tag :username, "Username" %>  
        <%= text_field_tag :username, "",class: "form-control input-sm chat-input"%>
        <%= label_tag :password, "Password" %>  
        <%= password_field_tag :password, "",class: "form-control input-sm chat-input"%>
      </br>
      <span class="group-btn">     
        <%= submit_tag "LOG IN", class: "btn btn-large btn-primary" %>
      </span>
      <span class="group-btn">
        <a href="/users/new" class="btn btn-primary btn-md">SIGN UP<i class="fa fa-sign-up"></i></a>  
      </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RailsBlog</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav class="navbar navbar-inverse">
		<ul class="nav navbar-nav">
			<% if current_user %>
			<li class="active"><a href="/users/<%=current_user.id if current_user %>/edit">Profile</a></li>
			<li><a href="/posts">Posts</a></li>
			<li><a href="/posts/new">Create Post</a></li>
			<li><%= link_to "LOGOUT", logout_path, class: "logout", method: :post if current_user%></li>
			<% end %>
		</ul>
	</nav>	
	<div>
		<% if flash[:notice] -%>
		<div class = "alert alert-success"><%= flash[:notice] %></div>
		<% end %>
		<%  if session[:user_id] %>
		<p style= "color:white; font-weight: bold;">You are logged in as: <%= current_user.username %></p>
		<% end %>
	</div>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/edit.html.erb
<div class = "col-md-offset-4 col-md-4">
	<%= form_for @post, html: {method: :patch} do |t| %> 
	<div class="form-login">
		<h4>EDIT POST</h4>
		<%= t.label :title, "TITLE" %> 
		<%= t.text_field :title,  class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= t.label :text, "TEXT" %> 
		<%= t.text_field :text, class: "form-control input-sm chat-input"%> 
	</div>	 
	<div class="wrapper">
		<%= t.submit class: "btn btn-primary btn-md", value: "Save Changes"%>
	</div>
	<% end %>
</div>

app/views/posts/index.html.erb
<div class="row">
	<% @posts.each do |post| %>
	<div class="title col-md-12"><%= post.title %></div>
	<div class="text col-md-12"><%= post.text %></div>
	<div class="image col-md-12"><%= image_tag post.image.url(:large) if post.image.exists? %></div>
	<% post.comments.each do |comment| %>
	<div class="comment col-md-12"><i><%= comment.user.username %> said </i> <%= comment.text %></div>
	<% end %>
	<div class="row">
		<% if current_user.id == post.user.id %>
		<div class="col-md-4"><%= link_to "Delete", post_path(post), class: "btn btn-primary btn-md", method: :delete %></div>
		<div class="col-md-4"><%= link_to "Edit", edit_post_path(post), class: "btn btn-primary btn-md" %></div>
		<% end %>
		<div class="col-md-4"><%= link_to "Comment", new_post_comment_path(post.id), class: "btn btn-primary btn-md" %></div>
	</div>
	<% end if @posts %>  
</div>

app/views/posts/new.html.erb
<div class = "col-md-offset-4 col-md-4">
	<%= form_for Post.new, html: { multipart: true } do |t| %> 
	<div class="form-login">
		<h4>NEW POST</h4>
		<%= t.label :title, "Title" %> 
		<%= t.text_field :title,  class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= t.label :text, "Text" %> 
		<%= t.text_field :text, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= t.label :image, "Image" %> 
		<%= t.file_field :image, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="wrapper">
		<%= t.submit class: "btn btn-primary btn-md", value: "CREATE POST"%>
	</div>
	<% end %>
</div>	

app/views/posts/show.html.erb
<table>
	<tr>
		<th>Post Id</th>
		<th>Title</th>
		<th>Text</th>
	</tr>
	<tr>
		<td><%= @post.id %></a></td>
		<td><%= @post.title %></td>
		<td><%= @post.text %></td>
	</tr>
</table> 

app/views/users/edit.html.erb
<h4>PULL YOURSELF TOGETHER FOR A SECOND!</h4>
<div class = "col-md-offset-4 col-md-4">
	<%= form_for @user, html: {method: :patch} do |f| %> 
	<div class="form-login">
		<h4>EDIT USER</h4>
		<%= f.label :fname, "First Name" %> 
		<%= f.text_field :fname,  class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :lname, "Last Name" %> 
		<%= f.text_field :lname, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :dob, "DOB" %> 
		<%= f.date_field :dob, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :username, "Username" %> 
		<%= f.text_field :username, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :password, "Current Password" %> 
		<%= f.password_field :password, class: "form-control input-sm chat-input", value: current_user.password%>
	</div>
	<div class="form-login">
		<%= f.label :new_password, "New Password" %> 
		<%= f.password_field :new_password, class: "form-control input-sm chat-input", value: current_user.password%>
	</div>	 
	<div class="wrapper">
		<%= f.submit class: "btn btn-primary btn-md", value: "Save Changes"%>
	</div>
	<% end %>
</div>

app/views/users/index.html.erb
 <h2>BLOG USERS</h2>
 </br>           
 <table class="table table-hover">
 	<thead>
 		<tr>
 			<th>User Id</th>
 			<th>First</th>
 			<th>Last</th>
 			<th>DOB</th>
 			<th>Username</th>
 			<th>Action</th>
 			<th>Action</th>
 		</tr>
 	</thead>
 	<tbody>
 		<% @users.each do |user| %>
 		<tr>
 			<td><a href="/users/<%= user.id %>"><%= user.id %></a></td>
 			<td><%= user.fname %></td>
 			<td><%= user.lname %></td>
 			<td><%= user.dob.strftime "%D" if user.dob %></td>
 			<td><%= user.username %></td>
 			<td><%= link_to "Delete", user_path(user), method: :delete %></td>
 			<td><%= link_to "Edit", edit_user_path(user) %></td>
 		</tr>
 		<% end %>
 	</tbody>
 </table>

app/views/users/new.html.erb
<h4>ONLY ONE STEP LEFT TO JOIN OUR COMMUNITY</h4>
<h4>YES WE KNOW SANITY IS OVERRATED!</h4>
<div class = "col-md-offset-4 col-md-4">
	<%= form_for User.new do |f| %> 
	<div class="form-login">
		<h4>NEW USER</h4>
		<%= f.label :fname, "First Name" %> 
		<%= f.text_field :fname,  class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :lname, "Last Name" %> 
		<%= f.text_field :lname, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :dob, "DOB" %> 
		<%= f.text_field :dob, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :username, "Username" %> 
		<%= f.text_field :username, class: "form-control input-sm chat-input"%> 
	</div>
	<div class="form-login">
		<%= f.label :password, "Password" %> 
		<%= f.text_field :password, class: "form-control input-sm chat-input"%>
	</div>
	<b></b>	 
	<div class="wrapper">
		<%= f.submit class: "btn btn-primary btn-md", value: "SIGNUP"%>
	</div>
	<% end %>
	<% if @user && @user.errors.full_messages.any? %> 
	<div class="form-login"> 
		<ul><% @user.errors.full_messages.each do |error_message| %>       
			<li><%= error_message %></li> 
			<br />     
			<% end %>   
		</ul>
	</div>
	<% end %>
</div>

app/views/users/show.html.erb
<table>
	<tr>
		<th>User Id</th>
		<th>First</th>
		<th>Last</th>
		<th>DOB</th>
		<th>Username</th>
	</tr>
	<tr>
		<td><%= @user.id %></a></td>
		<td><%= @user.fname %></td>
		<td><%= @user.lname %></td>
		<td><%= @user.dob.strftime "%D" if @user.dob %></td>
		<td><%= @user.username %></td>
	</tr>
</table> 